#!/usr/bin/env python3
"""
Build-time icon fetcher for the curated extension catalog.

For every id in src/renderer/src/data/extensionCatalog.ts it loads the Chrome
Web Store detail page, reads the og:image icon URL, downloads a small (64px)
PNG, and writes them all as base64 data URIs into
src/renderer/src/data/extensionCatalogIcons.ts.

Why data URIs: the picker must render icons with ZERO runtime network (CSP +
anti-detect ethos), so the bytes are inlined into the JS bundle at build time.
Re-run this whenever the catalog changes. Requires outbound network; failures
for a single id are skipped (the UI falls back to a generic glyph).

Usage:  python3 apps/desktop/scripts/fetch-catalog-icons.py
"""
import base64
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "src" / "renderer" / "src" / "data"
CATALOG = DATA / "extensionCatalog.ts"
OUT = DATA / "extensionCatalogIcons.ts"

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36"
ICON_PX = 64  # rendered small; 64 gives retina headroom while staying tiny


def get(url: str, binary: bool = False, timeout: int = 25):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        data = r.read()
    return data if binary else data.decode("utf-8", "replace")


def parse_ids_and_names(text: str):
    # Match { id: "...", name: "...", ... } entries in the catalog module.
    out = []
    for m in re.finditer(r'\{\s*id:\s*"([a-p]{32})",\s*name:\s*"((?:[^"\\]|\\.)*)"', text):
        out.append((m.group(1), m.group(2)))
    return out


def icon_url_for(ext_id: str):
    html = get(f"https://chromewebstore.google.com/detail/{ext_id}")
    m = re.search(r'<meta property="og:image" content="([^"]+)"', html)
    if not m:
        return None
    raw = m.group(1)
    # lh3 urls end with "=s128-rj-...": strip the size spec and ask for our size.
    base = raw.split("=")[0]
    return f"{base}=s{ICON_PX}"


def mime_of(data: bytes) -> str:
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return "image/png"
    if data[:3] == b"\xff\xd8\xff":
        return "image/jpeg"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "image/webp"
    return "image/png"


def main() -> int:
    text = CATALOG.read_text()
    entries = parse_ids_and_names(text)
    if not entries:
        print("no catalog entries found", file=sys.stderr)
        return 1

    icons: dict[str, str] = {}
    for ext_id, name in entries:
        try:
            url = icon_url_for(ext_id)
            if not url:
                print(f"  SKIP {name}: no og:image", file=sys.stderr)
                continue
            data = get(url, binary=True)
            if not data or len(data) > 200_000:  # sanity bound
                print(f"  SKIP {name}: bad icon ({len(data)}B)", file=sys.stderr)
                continue
            b64 = base64.b64encode(data).decode("ascii")
            icons[ext_id] = f"data:{mime_of(data)};base64,{b64}"
            print(f"  ok  {name} ({len(data)}B)")
        except Exception as e:  # noqa: BLE001 - best-effort per icon
            print(f"  SKIP {name}: {e}", file=sys.stderr)

    lines = [
        "// AUTO-GENERATED by scripts/fetch-catalog-icons.py — do not edit by hand.",
        "// Chrome Web Store icons for the curated catalog, inlined as base64 data",
        "// URIs so the picker renders them with zero runtime network (CSP +",
        "// anti-detect). Re-run the script after changing the catalog.",
        "",
        "export const CATALOG_ICONS: Record<string, string> = {",
    ]
    for ext_id, uri in icons.items():
        lines.append(f'  "{ext_id}": "{uri}",')
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {len(icons)}/{len(entries)} icons -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
